ServerEvents.recipes(event => {
    const gtr = event.recipes.gtceu

    gtr.molecular_transformer("gtocore:small_sunnarium_dust")
        .itemInputs("1x enderio:clayed_glowstone")
        .itemOutputs("1x gtceu:small_sunnarium_dust")
        .EUt(524288)
        .duration(200)

    gtr.molecular_transformer("gtocore:coal")
        .itemInputs("1x minecraft:charcoal")
        .itemOutputs("1x minecraft:coal")
        .EUt(120)
        .duration(200)

    gtr.molecular_transformer("gtocore:diamond")
        .itemInputs("4x minecraft:coal")
        .itemOutputs("1x minecraft:diamond")
        .EUt(7680)
        .duration(120)

    gtr.molecular_transformer("gtocore:nether_star")
        .itemInputs("2x minecraft:wither_skeleton_skull")
        .itemOutputs("1x minecraft:nether_star")
        .EUt(1920)
        .duration(800)

    gtr.molecular_transformer("gtocore:small_iridium_dust")
        .itemInputs("1x gtceu:small_platinum_dust")
        .itemOutputs("1x gtceu:small_iridium_dust")
        .EUt(480)
        .duration(400)

    gtr.molecular_transformer("gtocore:quartz_certus_quartz_crystal")
        .itemInputs("1x minecraft:quartz")
        .itemOutputs("1x ae2:certus_quartz_crystal")
        .EUt(120)
        .duration(160)

    gtr.molecular_transformer("gtocore:quartzite_certus_quartz_crystal")
        .itemInputs("1x gtceu:quartzite_gem")
        .itemOutputs("1x ae2:certus_quartz_crystal")
        .EUt(120)
        .duration(160)

    gtr.molecular_transformer("gtocore:powdered_coal")
        .itemInputs("2x gtceu:carbon_dust")
        .itemOutputs("1x enderio:powdered_coal")
        .EUt(120)
        .duration(200)

    gtr.molecular_transformer("gtocore:activated_carbon_dust")
        .itemInputs("1x enderio:powdered_coal")
        .itemOutputs("1x gtceu:activated_carbon_dust")
        .EUt(122880)
        .duration(20)

    gtr.molecular_transformer("gtocore:damascus_steel_dust")
        .itemInputs("1x gtceu:steel_dust")
        .itemOutputs("1x gtceu:damascus_steel_dust")
        .EUt(480)
        .duration(20)

    gtr.molecular_transformer("gtocore:wrought_iron_dust")
        .itemInputs("1x enderio:powdered_iron")
        .itemOutputs("1x gtceu:wrought_iron_dust")
        .EUt(120)
        .duration(20)

    gtr.molecular_transformer("gtocore:steel_dust")
        .itemInputs("1x gtceu:wrought_iron_dust")
        .itemOutputs("1x gtceu:steel_dust")
        .EUt(480)
        .duration(80)

    gtr.molecular_transformer("gtocore:bone")
        .itemInputs("6x minecraft:bone_meal")
        .itemOutputs("1x minecraft:bone")
        .EUt(30)
        .duration(40)

    gtr.molecular_transformer("gtocore:small_bone_dust")
        .itemInputs("1x gtceu:small_calcium_dust")
        .itemOutputs("1x gtceu:small_bone_dust")
        .EUt(30)
        .duration(20)

    gtr.molecular_transformer("gtocore:energy_crystal")
        .itemInputs("1x gtceu:exquisite_ruby_gem")
        .itemOutputs("2x gtceu:energy_crystal")
        .EUt(524288)
        .duration(200)

    gtr.molecular_transformer("gtocore:lapotron_gem")
        .itemInputs("1x gtceu:exquisite_sodalite_gem")
        .itemOutputs("1x gtceu:lapotron_gem")
        .EUt(524288)
        .duration(800)

})