name = "GregTech Odyssey"
version = "0.2.9-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "402b91c47adb8a412d0e9fa603303d83fa62a9f125fe3e4e10ed80b1f4f26aac"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
