name = "GregTech Odyssey"
version = "0.2.9-beta"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d66b52b3add3efd30bc38b224f03ba02e542180d952cc30233d80dc1ec79bf12"

[versions]
forge = "47.4.1"
minecraft = "1.20.1"
