name: Bug Report
description: Report a bug where something is not working as expected.
labels: [ "type: bug" ]
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Checked for existing issues
      description: You have checked for existing reports of this issue, open or closed.
      options:
        - label: "I have checked for existing issues, and have found none."
          required: true
  - type: checkboxes
    id: tried-latest
    attributes:
      label: Tested latest version
      description: You have checked that this issue occurs on the latest version.
      options:
        - label: "I have checked that this occurs on the latest version."
          required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      description: "How you were playing on the world. Typical answers include: Singleplayer, Open to LAN, Dedicated Server."
      placeholder: "Example: Singleplayer"
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen. Attach screenshots here as necessary.
      placeholder: "Example: Expected to produce X by consuming Y."
    validations:
      required: true
  - type: textarea
    id: result
    attributes:
      label: Actual Behavior
      description: What happened despite your expectations. Attach screenshots here as necessary.
      placeholder: "Example: Produced one X but Y was not consumed."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: How to reproduce the bug.
      placeholder: "Example: 1) I did X..."
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional information you wish to provide. Please add anything which did not fit into the other sections here.
      placeholder: "Example: This is likely caused by X because..."
    validations:
      required: false
  - type: markdown
    attributes:
      value: Thank you for taking the time to fill out this bug report.
